### ISSUE TITLE
Count To from x to 0, results in -0

### ISSUE THREAD

**Issue by jjrchrds** [mhuggins/jquery-countTo#30] opened 2015-01-27 12:37 UTC
Not sure why but occasionally when counting from certain numbers to zero, I end up with -0 being displayed. The number passed in the TO: field is zero.

**Comment by mhuggins** [comment] 2015-02-06 00:18
I'm willing to bet this is an issue with using floats.  It's probably a number like -0.00000000001 or something behind the scenes that's rendering as -0.  I'll have to dig deeper.  Do you have sample code you could share that caused this?

**Comment by mhuggins** [comment] 2017-02-02 21:22
Closing as duplicate of #52.  I know this one was opened first, but that one includes a workaround, which I think some people will find useful.

**Closed by mhuggins** 2017-02-02 21:22 UTC
