### ISSUE TITLE
-0 ?

### ISSUE THREAD

**Issue by Noitidart** [mhuggins/jquery-countTo#52] opened 2015-09-17 16:30 UTC
I'm doing a

   $el.countTo({from:2, to:0});

so from 2 to 0, count down, i have data-speed on the elment set to 2000. How come it takes me to `-0`? It should be just `0`

**Comment by Noitidart** [comment] 2015-09-17 16:33
Also go to -0 when i do a from 1 to 0. Doing a from 3 to 0 does not give me -0.

**Comment by thomjjames** [comment] 2017-02-02 15:32
Hi,

I had this too, I used the "formatter" callback option to work around it:

> `$('.count-to').countTo({
>             onComplete: function() {
>               $('.count-to').addClass('count-to-done');
>             },
>             formatter: function (value, options) {
>               var v = value.toFixed(options.decimals);
>               if (v == '-0') {
>                 v = '0';
>               }
>               return v;
>             },
>           });`

Hope that helps
Tom

**Comment by plaidman** [comment] 2017-04-18 19:15
The cause of this bug is because of compounding floating point additions causes rounding errors to add up. Sometimes you will get an infinitesimally small negative number (`-0.00000000000001`) instead of true zero. This is normal computery stuff, so there's really nothing we can do about that.

The REAL problem comes with `Number.toFixed()` being dumb, so it just chops off the trailing decimal places and calls it done, instead of analyzing the returned value and making sure it makes sense to normal people. JS is great!

In Tom's solution, it wouldn't work if you're trying to round to more than zero decimals. There are some cases where you would get `-0.000`, which is equally nonsense. I have a proposed solution to work for all precisions:

```js
var settings = {
  formatter: function (value, settings) {
    value = value.toFixed(settings.decimals);
    value = value.replace(/\B(?=(\d{3})+(?!\d))/g, ',');

    if (1 / value === -Infinity) {
      //strip the negative
      value = value.substring(1);
    }

    return value;
  }
}

$('count-to').countTo(settings);
```

This works because `1/0` is `Infinity`, so obviously `1/-0` is `-Infinity`. Yay pseudo-math!

@mhuggins can add the new conditional to countTo.jquery.js, I think that will work for all cases.

**Comment by tommy20061222** [comment] 2017-04-18 19:54
@plaidman this might be another way to solve your problem: https://github.com/ljharb/is-negative-zero/blob/master/index.js

` (1 / number) === -Infinity;`

**Comment by plaidman** [comment] 2017-04-18 19:58
I like that one better too, and it works for reasons other than because JS is weird. I edited my solution above.

**Comment by mhuggins** [comment] 2019-10-12 18:01
Closing due to suggested solutions being provided.

**Closed by mhuggins** 2019-10-12 18:01 UTC
